### ISSUE TITLE
Knowing your limits

### ISSUE THREAD

**Issue by piratestatic** [offensive-security/nethunter-devices#11]
So what are major/hard limits to a device not being able to support Nethunter/Kali Linux mobile? At first I thought it was the Snapdragon 800 series processor but it seems that isn't the case. 

I was also looking at the Pwn Phone by Pwnie Express (https://www.pwnieexpress.com/build-pwn-phone) and their builds aren't as expansive as the Nethunters but they are working on releasing the exact same ones. That may be due to taking the easy route out and not re-inventing the wheel. 

I am just curious from the developers side why certain phones are able to and others that seem to be running the same operation system and can be unlocked, can't run Nethunter.

**Comment by binkybear** [comment]
Limits:
- Kernel version
- Unlockable bootloader
- Memory/Hard drive space
- OTG Capable
- TWRP

Technically if it has TWRP and a newish kernel (probably after 2012) you can run Nethunter.  What separates the devices is we build custom kernels for wireless device support/hid/drivedroid.  If you don't want those things anyone can flash a generic version.

I haven't used a Pwnie in a very long time but I know they build ROM images instead and focus on a few devices.  Our builds are flashed over stock images and can gone on a lot more devices.  The downside is that each device is different and testing is difficult.
