### ISSUE TITLE
Zte Axon 7 no Sound via Speakers

### ISSUE THREAD

**Issue by H4xl0r** [offensive-security/nethunter-devices#122]
### Device:
ZTE Axon7 Europe (A2017G_8433)

### OS version (KitKat/Lollipop/Marshmallow/Nougat):
Marshmallow (6.0.1)

### Built from repo (date and build command) or downloaded from website (links):
https://forum.xda-developers.com/axon-7/development/kernel-kali-nethunter-zte-axon-7-t3520280 
btw:
http://build.nethunter.com/nightly/

### Output of `cat /proc/version` in adb shell or NetHunter Terminal:
Linux version 3.18.47-nethunter-ailsa_ii-3.1 (jc@westerley)
(gcc version 5.3.1 20160412 (Linaro GCC 5.3-2016.05) #1 SMP PREEMPT Sun Jan 22 22:35:19 EST 2017

## Issue:

All working fine, but no sound from Speakers, headphones are still working.

flashed kernel again no afford ....

**Comment by jcadduono** [comment]
have to switch to USA or China rom

**Comment by H4xl0r** [comment]
could you please give me the link ? is it a know error ?
do i understand it right, that i have to switch the kernel , because there is only one offered on 
https://build.nethunter.com/nightly/2017.11-18-1618/ 

or do you mean to reset the phone to stock usa firmware and then flash it again ?
would be nice to have the speakers also working, as i said before the rest is working fine so thanks for the work....
