### ISSUE TITLE
OnePlus-3T-oos have not cdc_acm.ko 

### ISSUE THREAD

**Issue by SpenserCai** [offensive-security/nethunter-devices#135]
I want connect proxmark3 on Nethunter but I can't find cdc_acm.ko, my phone is oneplus3t use nethunter-oos rom.

**Comment by SpenserCai** [comment]
how to build OnePlus-3T-oos's kernel I don't know use witch project

**Comment by Re4son** [comment]
Someone has to rebuild the kernel with the following option set:

CONFIG_USB_ACM=[y/m]

We'll update the wiki accordingly
