### ISSUE TITLE
Pie support missing

### ISSUE THREAD

**Issue by theimprobableoneATSH** [offensive-security/nethunter-devices#173]
Android Version: 9.0 (Pie)
Device-Zuk Z2 Plus
Hi can someone tell me how can I make pie kernel flashable zip(using build.py). I have succesfully compiled the kernel but in this devices section the support ends till oreo..How can i add my device under android pie and build it using build.py....
Also how can I apply HiD Patch to it ? Bcoz i have currently compiled the kernel without it..

**Comment by Re4son** [comment]
Done. Just do a pull and you'll see a pie folder.
The nethunter-installer has been updated to support pie using the command line argument "--pie" or "-p".
