### ISSUE TITLE
ZTE Axon Any Updates ?

### ISSUE THREAD

**Issue by H4xl0r** [offensive-security/nethunter-devices#180]
Device:

ZTE Axon7 Europe (A2017G_8433)
OS version (KitKat/Lollipop/Marshmallow/Nougat):

Marshmallow (6.0.1)

IS THERE ANY NEW UPDATE KERNEL FOR NEWER VERSION AND USB HID comming ? 
or do i need to buy another phone ?

**Comment by Re4son** [comment]
I'm not aware of anyone working on it at the moment but that wouldn't make me throw away the phone. More likely the opposite: I'd create my own kernel using the sources made available through the xda forums. Interested?
https://forum.xda-developers.com/axon-7/how-to/summary-best-pie-roms-to-try-to-moment-t3841784

**Comment by H4xl0r** [comment]
sure if we get a higher working version including usb drivers etc ... would be nice

**Comment by Re4son** [comment]
Please reopen this issue if you need any support
