### ISSUE TITLE
OnePlus One HID attacks

### ISSUE THREAD

**Issue by bkr32** [offensive-security/nethunter-devices#29]
DuckHunter and HID attacks aren't working from the nethunter app however the HID USB keyboard app is working fine, something broken in nethunter or kernel?
@binkybear

**Comment by bkr32** [comment]
metapackage update fixed it

**Comment by binkybear** [comment]
Hmm interesting.  More than one person mentioned it wasn't working (hid) in new app.  I haven't been able to recreate this issue though.

**Comment by bkr32** [comment]
Well for me it was
Wipe system and cache and dalvik cache
Reflash system 
Reboot 
Reflash nethunter 
HID doesn't work
Update metapackages
This was just to get rid of a few battery issues
