### ISSUE TITLE
[oneplus2cm] kernel broken for latest builds of CM13

### ISSUE THREAD

**Issue by 1nt3rnal3rr0r** [offensive-security/nethunter-devices#40]
The oneplus2cm kernel does not work as stated in the title. The phone just hangs at the oneplus logo. I think that a possible solution would be to build a new custom kernel against the latest stock CM13 kernel. I would do it myself, but I am quite afraid to mess something up and blow up my phone :smile: .

**Comment by Re4son** [comment]
Kernels for CM14, 15, & 16 work
