### ISSUE TITLE
Wireless Card Not Detecting

### ISSUE THREAD

**Issue by AgentBaphomet** [offensive-security/nethunter-devices#67]
Device: OnePlus One
ROM: CM12.1
Root: SuperSU v.2.79
ROM State: clean install 
Kernel: Newest as of 12/22/2016 

This kernel version does not detect my  TL-WN722N or any wireless cards.  To ensure it was a kernel issue, I flashed the kernel version 3.4.67 built december 13. Now it works but this old kernel has the sleep of death issue.

**Comment by jcadduono** [comment]
cat /proc/version

**Comment by AgentBaphomet** [comment]
Kernel: 3.4.67 (built sat feb 6 2016) first post updated
